---

- name: Find location of manage.py
  find:
    paths: "{{ ENV_PATH }}"
    file_type: file
    use_regex: yes
    patterns: "^.*manage.py$"
    recurse: yes
  register: output

- set_fact:
    MANAGE_FILE: "{{ output.files[0].path}}"
  when: output != ""

- debug:
    msg: "manage.py is found at :{{MANAGE_FILE}}"
    verbosity: "{{ verbosity_level }}"
