
- set_fact:
    sys_nova_pth: /openstack/venvs/nova-{{ venv_tag }}

- name: Get nova venv path
  shell: echo {{ sys_nova_pth }}
  register: pre_def_pth
  when: nova_virtual_env is undefined

- name: Get nova venv path when nova_virtual_env is passed
  shell: echo {{ nova_virtual_env }}
  register: pre_usr_pth
  when: nova_virtual_env is defined

- name: Check stat default nova virt path
  stat:
    path: "{{ sys_nova_pth }}"
  register: chk_def_pth
  when: nova_virtual_env is undefined
   
- name: Check stat user provided nova virt path
  stat:
    path: "{{ nova_virtual_env }}"
  register: chk_usr_pth
  when: nova_virtual_env is defined

- set_fact: 
    virtual_env_path: "{{ pre_def_pth.stdout }}"
  when:
    - chk_def_pth.stat.exists == true
    - nova_virtual_env is undefined

- set_fact: 
    virtual_env_path: "{{ pre_usr_pth.stdout }}"
  when:
    - chk_usr_pth.stat.exists == true
    - nova_virtual_env is defined

- set_fact:
    virtual_env: ". {{virtual_env_path}}/bin/activate"

- set_fact: NOVA_COMPUTE_FILTERS_FILE={{virtual_env_path}}/etc/nova/rootwrap.d/compute.filters

- debug:
    msg: "NOVA_COMPUTE_FILTERS_FILE: {{NOVA_COMPUTE_FILTERS_FILE}}"
    verbosity: "{{ verbosity_level }}"
