
- set_fact:
    sys_nova_pth: /openstack/venvs/nova-{{ venv_tag }}

- name: Check stat default nova virt path
  stat:
    path: "{{ sys_nova_pth }}"
  register: chk_def_pth
  when: nova_virtual_env is undefined
   
- name: Check stat user provided nova virt path
  stat:
    path: "{{ nova_virtual_env }}"
  register: chk_usr_pth
  when: nova_virtual_env is defined

- set_fact: 
    virtual_env_path: "{{ sys_nova_pth }}"
  when: >
        ( nova_virtual_env is undefined ) and
        ( chk_def_pth.stat.exists == true )

- set_fact: 
    virtual_env_path: "{{ nova_virtual_env }}"
  when: > 
        ( nova_virtual_env is defined ) and
        ( chk_usr_pth.stat.exists == true )

- set_fact:
    virtual_env: ". {{virtual_env_path}}/bin/activate"

- set_fact: NOVA_COMPUTE_FILTERS_FILE={{virtual_env_path}}/etc/nova/rootwrap.d/compute.filters

- debug:
    msg: "NOVA_COMPUTE_FILTERS_FILE: {{NOVA_COMPUTE_FILTERS_FILE}}"
    verbosity: "{{ verbosity_level }}"
